train_file: ["../data/rshaojimmy/DGM4/metadata/train.json"]
# train_file: ["Train.json"]
# val_file: ["val.json"]
val_file: ["../data/rshaojimmy/DGM4/metadata/val.json"] 
visual_file: ["/workspace/Crilias/coDE/image.json"]   
bert_config: 'configs/config_bert.json'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size_train: 32
batch_size_val: 128
temp: 0.07
queue_size: 65536
momentum: 0.995
alpha: 0.4
max_words: 50
label_smoothing: 0.0

loss_MAC_wgt: 0.1
loss_BIC_wgt: 1
loss_bbox_wgt: 0.1
loss_giou_wgt: 0.1
loss_TMG_wgt: 1
loss_MLC_wgt: 1

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 50, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-6, warmup_epochs: 10, cooldown_epochs: 0}







